In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Google Drive에서 CSV 파일 경로 지정
salary_file_path = '/content/drive/MyDrive/ajou/41_ML/project/basic data/all_salary_data_2.csv'

# Pandas를 사용하여 CSV 파일을 로드
import pandas as pd

# 선수 계약 정보 데이터 로드
salary_df = pd.read_csv(salary_file_path, encoding='ISO-8859-1')

# 데이터의 첫 몇 행을 확인
salary_df.head()

           name debut  start   end     salary    target
0   A.J. Lawson  2021   2023  2026  1978006.0  0.013971
1  Aaron Brooks  2007   2012  2013  3323125.0  0.057252
2  Aaron Brooks  2007   2012  2013  2454000.0  0.042278
3  Aaron Brooks  2007   2015  2015  2250000.0  0.032143
4  Aaron Brooks  2007   2016  2016  2700000.0  0.028680

In [ ]:
# salary 열을 숫자 형식으로 변환
salary_df['salary'] = pd.to_numeric(salary_df['salary'], errors='coerce')

# salary가 NaN인 행 제거
salary_df = salary_df.dropna(subset=['salary'])

# salary 하위 5% 임계값 계산
threshold = salary_df['salary'].quantile(0.05)

# 임계값을 초과하는 행만 필터링
filtered_salary_df = salary_df[salary_df['salary'] > threshold]

# 결과 확인
print(filtered_salary_df.head())

           name debut  start   end     salary    target
0   A.J. Lawson  2021   2023  2026  1978006.0  0.013971
1  Aaron Brooks  2007   2012  2013  3323125.0  0.057252
2  Aaron Brooks  2007   2012  2013  2454000.0  0.042278
3  Aaron Brooks  2007   2015  2015  2250000.0  0.032143
4  Aaron Brooks  2007   2016  2016  2700000.0  0.028680

In [ ]:
# 결과를 Google Drive에 새로운 CSV 파일로 저장하기
output_filtered_file = '/content/drive/MyDrive/ajou/41_ML/project/modified data/filtered_all_salary_data.csv'
filtered_salary_df.to_csv(output_filtered_file, index=False)

print(f'Saved filtered file to {output_filtered_file}')

Saved filtered file to /content/drive/MyDrive/ajou/41_ML/project/modified data/filtered_all_salary_data.csv

In [17]:
# Google Drive에서 CSV 파일 경로 지정
filtered_salary_file_path = '/content/drive/MyDrive/ajou/41_ML/project/modified data/filtered_all_salary_data.csv'

# Pandas를 사용하여 CSV 파일을 로드
import pandas as pd

# Pandas를 사용하여 CSV 파일을 로드 (cp1252 인코딩 사용)
original_data = pd.read_csv(filtered_salary_file_path, encoding='cp1252')

# 'name'과 'start'로 그룹화하여 'salary', 'target', 'debut'의 평균 계산
grouped_data = original_data.groupby(['name', 'start']).agg({'salary': 'mean', 'target': 'mean', 'debut': 'mean'}).reset_index()

# 'debut' 열을 정수로 변환
grouped_data['debut'] = grouped_data['debut'].astype(int)

# 새로운 CSV 파일로 그룹화된 데이터 저장
new_file_path = '/content/drive/MyDrive/ajou/41_ML/project/modified data/salary_deduplication.csv'
grouped_data.to_csv(new_file_path, index=False)